source 'https://rubygems.org'
gem 'middleman', '~> 3.3.8'
gem 'middleman-core', '~> 3.3.8'
gem 'middleman-sprockets', '~> 3.4.1'
gem 'middleman-livereload', '~> 3.4.2'
gem 'sprockets-babel', '~> 0.0.1'
gem 'babel-source', '~> 5.0.12'
gem 'uglifier', '~> 2.7.1'
gem 'therubyracer', '~> 0.12.1'
