source 'https://rubygems.org'
gem 'middleman', '~> 3.3.12'
gem 'middleman-core', '~> 3.3.12'
gem 'middleman-sprockets', '~> 3.4.2'
gem 'middleman-livereload', '~> 3.4.2'
gem 'sprockets-babel', '~> 0.0.3'
gem 'babel-source', '~> 5.4.3'
